# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
os: linux
dist: bionic
cache: packages

before_deploy:
  - R -e "install.packages('roxygen2', repos = 'http://cran.rstudio.com')"
